name: V2 CI

on:
  push:
    paths:
    - 'v2/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'v2/.go-version'
          cache: true
          cache-dependency-path: v2/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.6.1
          working-directory: v2
          args: --config=.golangci.yml

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: v2

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'v2/.go-version'
          cache: true
          cache-dependency-path: v2/go.sum

      - name: Run Unit Tests
        run: make test
